name: Generate Contribution Snake

on:
  schedule:
    - cron: "0 0 * * *" # Runs once a day at midnight UTC
  workflow_dispatch: # Allow manual trigger
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: Ignite7871
          outputs: dist/github-contribution-grid-snake.svg

      - name: Push Snake Animation to the output branch
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "Generated contribution snake"
          add: "dist/github-contribution-grid-snake.svg"

